query($addr: String!, $id: [String!]!, $cursor: String) {
  transactions(
    owners: [$addr]
    tags: [
      { name: "App-Name", values: "Sera" }
      { name: "ID", values: $id }
      { name: "Action", values: "Edit" }
    ]
    after: $cursor
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      cursor
      node {
        id
      }
    }
  }
}
